#!/bin/sh
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chan1.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chan2.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chan3.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chan4.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chan6.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chan7.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chan8.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chanB.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chanC.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chanD.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chanE.sph
wget    -P Signals/Bdb001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bdb001/chanF.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chan0.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chan1.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chan2.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chan3.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chan4.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chan6.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chan7.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chan8.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chanB.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chanC.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chanD.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chanE.sph
wget    -P Signals/Bed002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed002/chanF.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chan1.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chan2.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chan3.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chan4.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chan6.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chan7.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chanC.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chanD.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chanE.sph
wget    -P Signals/Bed003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed003/chanF.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chan1.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chan2.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chan3.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chan4.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chan6.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chan7.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chanC.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chanD.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chanE.sph
wget    -P Signals/Bed004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed004/chanF.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chan0.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chan1.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chan2.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chan3.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chan4.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chan5.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chan6.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chan7.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chanC.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chanD.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chanE.sph
wget    -P Signals/Bed005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed005/chanF.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chan0.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chan1.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chan2.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chan3.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chan4.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chan5.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chan6.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chan7.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chanA.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chanC.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chanD.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chanE.sph
wget    -P Signals/Bed006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed006/chanF.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chan0.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chan2.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chan3.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chan4.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chan5.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chan6.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chan7.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chanC.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chanD.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chanE.sph
wget    -P Signals/Bed008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed008/chanF.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan0.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan1.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan2.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan3.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan4.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan5.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan6.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan7.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chan8.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chanC.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chanD.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chanE.sph
wget    -P Signals/Bed009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed009/chanF.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan0.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan1.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan2.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan3.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan4.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan5.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan6.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan7.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chan9.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chanC.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chanD.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chanE.sph
wget    -P Signals/Bed010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed010/chanF.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chan0.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chan1.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chan2.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chan3.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chan4.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chan5.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chan6.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chan7.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chanA.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chanC.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chanD.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chanE.sph
wget    -P Signals/Bed011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed011/chanF.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chan1.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chan2.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chan3.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chan4.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chan6.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chan7.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chanC.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chanD.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chanE.sph
wget    -P Signals/Bed012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed012/chanF.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chan0.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chan1.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chan2.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chan3.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chan4.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chan5.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chan6.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chan7.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chanC.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chanD.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chanE.sph
wget    -P Signals/Bed013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed013/chanF.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chan0.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chan1.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chan2.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chan3.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chan4.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chan5.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chan6.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chan7.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chanC.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chanD.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chanE.sph
wget    -P Signals/Bed014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed014/chanF.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chan0.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chan1.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chan2.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chan3.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chan4.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chan5.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chan6.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chan7.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chanC.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chanD.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chanE.sph
wget    -P Signals/Bed015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed015/chanF.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chan1.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chan2.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chan3.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chan4.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chan5.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chan6.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chan7.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chan9.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chanC.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chanD.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chanE.sph
wget    -P Signals/Bed016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed016/chanF.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chan0.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chan1.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chan2.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chan3.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chan4.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chan5.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chan6.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chan7.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chanC.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chanD.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chanE.sph
wget    -P Signals/Bed017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bed017/chanF.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chan0.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chan1.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chan6.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chan7.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chan8.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chanC.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chanD.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chanE.sph
wget    -P Signals/Bmr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr001/chanF.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chan0.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chan1.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chan2.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chan3.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chan6.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chan7.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chan8.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chanC.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chanD.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chanE.sph
wget    -P Signals/Bmr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr002/chanF.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan0.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan1.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan2.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan3.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan4.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan6.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan7.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan8.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chan9.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chanE.sph
wget    -P Signals/Bmr003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr003/chanF.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan0.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan1.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan2.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan3.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan4.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan5.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan6.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan7.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chan8.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chanB.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chanC.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chanD.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chanE.sph
wget    -P Signals/Bmr005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr005/chanF.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chan0.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chan1.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chan2.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chan3.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chan4.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chan6.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chan7.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chan9.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chanC.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chanD.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chanE.sph
wget    -P Signals/Bmr006 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr006/chanF.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chan0.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chan1.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chan2.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chan3.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chan4.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chan6.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chan7.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chan8.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chanA.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chanB.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chanC.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chanD.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chanE.sph
wget    -P Signals/Bmr007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr007/chanF.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chan0.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chan1.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chan2.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chan3.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chan4.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chan6.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chan7.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chan8.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chanC.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chanD.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chanE.sph
wget    -P Signals/Bmr008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr008/chanF.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chan0.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chan1.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chan2.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chan3.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chan4.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chan6.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chan7.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chanC.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chanD.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chanE.sph
wget    -P Signals/Bmr009 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr009/chanF.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chan0.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chan1.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chan2.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chan3.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chan4.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chan6.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chan7.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chan8.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chanB.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chanC.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chanD.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chanE.sph
wget    -P Signals/Bmr010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr010/chanF.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan0.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan1.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan2.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan3.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan4.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan5.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan6.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan7.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chan8.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chanB.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chanC.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chanD.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chanE.sph
wget    -P Signals/Bmr011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr011/chanF.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan0.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan1.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan2.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan3.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan4.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan5.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan6.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan7.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chan8.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chanB.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chanC.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chanD.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chanE.sph
wget    -P Signals/Bmr012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr012/chanF.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chan1.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chan2.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chan3.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chan4.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chan5.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chan6.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chan7.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chan8.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chanB.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chanC.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chanD.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chanE.sph
wget    -P Signals/Bmr013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr013/chanF.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chan1.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chan2.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chan4.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chan5.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chan6.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chan7.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chan8.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chanB.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chanC.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chanD.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chanE.sph
wget    -P Signals/Bmr014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr014/chanF.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chan1.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chan2.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chan3.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chan4.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chan5.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chan6.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chan7.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chan8.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chanB.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chanC.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chanD.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chanE.sph
wget    -P Signals/Bmr015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr015/chanF.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chan1.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chan2.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chan3.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chan4.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chan5.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chan6.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chan7.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chan8.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chanB.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chanC.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chanD.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chanE.sph
wget    -P Signals/Bmr016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr016/chanF.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan0.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan1.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan2.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan3.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan4.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan5.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan6.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan7.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chan8.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chanC.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chanD.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chanE.sph
wget    -P Signals/Bmr018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr018/chanF.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan0.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan1.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan2.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan3.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan4.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan5.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan6.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan7.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chan8.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chanA.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chanB.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chanC.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chanD.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chanE.sph
wget    -P Signals/Bmr019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr019/chanF.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chan0.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chan1.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chan2.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chan3.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chan4.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chan5.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chan6.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chan7.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chanA.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chanC.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chanD.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chanE.sph
wget    -P Signals/Bmr020 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr020/chanF.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chan0.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chan1.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chan2.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chan3.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chan4.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chan5.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chan6.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chan7.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chanC.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chanD.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chanE.sph
wget    -P Signals/Bmr021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr021/chanF.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chan0.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chan1.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chan2.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chan3.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chan5.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chan6.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chan7.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chanA.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chanC.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chanD.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chanE.sph
wget    -P Signals/Bmr022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr022/chanF.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan0.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan1.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan2.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan3.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan4.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan5.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan6.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan7.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chan9.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chanC.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chanD.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chanE.sph
wget    -P Signals/Bmr023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr023/chanF.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan0.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan1.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan2.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan3.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan4.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan5.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan6.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan7.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chan9.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chanA.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chanB.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chanC.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chanD.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chanE.sph
wget    -P Signals/Bmr024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr024/chanF.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan0.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan1.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan2.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan3.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan4.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan5.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan6.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan7.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chan9.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chanA.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chanC.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chanD.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chanE.sph
wget    -P Signals/Bmr025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr025/chanF.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chan0.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chan1.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chan2.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chan3.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chan4.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chan5.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chan6.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chan7.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chanC.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chanD.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chanE.sph
wget    -P Signals/Bmr026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr026/chanF.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan0.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan1.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan2.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan3.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan4.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan5.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan6.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan7.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chan9.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chanB.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chanC.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chanD.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chanE.sph
wget    -P Signals/Bmr027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr027/chanF.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan0.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan1.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan2.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan3.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan4.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan5.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan6.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan7.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chan9.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chanA.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chanB.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chanC.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chanD.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chanE.sph
wget    -P Signals/Bmr028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr028/chanF.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chan0.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chan1.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chan2.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chan3.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chan4.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chan6.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chan7.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chan9.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chanC.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chanD.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chanE.sph
wget    -P Signals/Bmr029 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr029/chanF.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chan1.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chan2.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chan3.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chan4.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chan5.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chan6.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chan7.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chanC.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chanD.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chanE.sph
wget    -P Signals/Bmr030 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr030/chanF.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan0.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan1.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan2.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan3.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan4.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan5.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan6.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan7.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chan9.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chanA.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chanB.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chanC.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chanD.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chanE.sph
wget    -P Signals/Bmr031 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bmr031/chanF.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chan0.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chan1.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chan2.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chan3.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chan4.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chan6.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chan7.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chan8.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chanA.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chanC.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chanD.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chanE.sph
wget    -P Signals/Bns001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns001/chanF.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chan0.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chan1.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chan3.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chan4.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chan6.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chan7.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chanB.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chanC.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chanD.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chanE.sph
wget    -P Signals/Bns002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns002/chanF.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chan0.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chan1.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chan2.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chan4.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chan6.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chan7.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chan8.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chanA.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chanC.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chanD.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chanE.sph
wget    -P Signals/Bns003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bns003/chanF.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan0.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan1.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan2.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan3.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan4.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan6.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan7.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan8.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chan9.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chanC.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chanD.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chanE.sph
wget    -P Signals/Bro003 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro003/chanF.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chan0.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chan1.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chan2.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chan3.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chan4.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chan6.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chan7.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chan9.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chanB.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chanC.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chanD.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chanE.sph
wget    -P Signals/Bro004 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro004/chanF.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chan0.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chan1.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chan2.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chan4.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chan6.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chan7.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chanB.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chanC.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chanD.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chanE.sph
wget    -P Signals/Bro005 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro005/chanF.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chan0.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chan1.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chan2.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chan3.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chan6.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chan7.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chanB.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chanC.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chanD.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chanE.sph
wget    -P Signals/Bro007 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro007/chanF.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chan1.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chan2.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chan3.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chan4.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chan5.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chan6.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chan7.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chanC.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chanD.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chanE.sph
wget    -P Signals/Bro008 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro008/chanF.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chan2.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chan3.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chan4.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chan5.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chan6.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chan7.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chan8.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chanB.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chanC.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chanD.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chanE.sph
wget    -P Signals/Bro010 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro010/chanF.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chan1.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chan2.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chan3.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chan4.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chan6.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chan7.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chan8.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chanB.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chanC.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chanD.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chanE.sph
wget    -P Signals/Bro011 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro011/chanF.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chan0.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chan1.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chan2.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chan3.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chan4.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chan5.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chan6.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chan7.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chanC.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chanD.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chanE.sph
wget    -P Signals/Bro012 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro012/chanF.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chan0.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chan1.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chan3.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chan4.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chan5.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chan6.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chan7.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chanC.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chanD.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chanE.sph
wget    -P Signals/Bro013 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro013/chanF.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chan0.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chan1.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chan2.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chan3.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chan4.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chan5.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chan6.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chan7.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chanC.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chanD.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chanE.sph
wget    -P Signals/Bro014 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro014/chanF.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chan0.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chan1.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chan2.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chan3.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chan4.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chan5.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chan6.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chan7.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chanC.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chanD.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chanE.sph
wget    -P Signals/Bro015 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro015/chanF.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chan0.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chan1.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chan2.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chan3.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chan4.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chan5.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chan6.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chan7.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chanC.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chanD.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chanE.sph
wget    -P Signals/Bro016 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro016/chanF.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chan0.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chan1.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chan3.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chan4.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chan5.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chan6.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chan7.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chanC.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chanD.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chanE.sph
wget    -P Signals/Bro017 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro017/chanF.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chan0.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chan1.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chan2.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chan4.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chan5.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chan6.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chan7.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chanC.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chanD.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chanE.sph
wget    -P Signals/Bro018 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro018/chanF.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chan0.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chan1.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chan2.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chan3.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chan4.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chan5.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chan6.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chan7.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chanB.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chanC.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chanD.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chanE.sph
wget    -P Signals/Bro019 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro019/chanF.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chan0.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chan1.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chan2.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chan3.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chan4.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chan5.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chan6.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chan7.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chanB.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chanC.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chanD.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chanE.sph
wget    -P Signals/Bro021 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro021/chanF.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chan0.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chan1.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chan2.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chan3.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chan4.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chan5.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chan6.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chan7.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chanB.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chanC.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chanD.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chanE.sph
wget    -P Signals/Bro022 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro022/chanF.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chan0.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chan1.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chan2.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chan3.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chan6.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chan7.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chanB.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chanC.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chanD.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chanE.sph
wget    -P Signals/Bro023 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro023/chanF.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chan0.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chan1.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chan2.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chan3.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chan4.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chan5.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chan6.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chan7.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chanA.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chanB.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chanC.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chanD.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chanE.sph
wget    -P Signals/Bro024 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro024/chanF.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chan0.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chan1.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chan2.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chan3.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chan5.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chan6.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chan7.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chanC.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chanD.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chanE.sph
wget    -P Signals/Bro025 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro025/chanF.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chan0.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chan2.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chan3.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chan4.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chan5.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chan6.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chan7.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chanC.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chanD.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chanE.sph
wget    -P Signals/Bro026 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro026/chanF.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chan0.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chan1.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chan3.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chan4.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chan6.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chan7.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chanC.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chanD.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chanE.sph
wget    -P Signals/Bro027 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro027/chanF.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chan0.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chan1.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chan2.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chan4.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chan5.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chan6.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chan7.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chanC.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chanD.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chanE.sph
wget    -P Signals/Bro028 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bro028/chanF.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan0.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan1.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan2.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan3.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan4.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan6.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan7.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan8.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chan9.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chanA.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chanB.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chanC.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chanD.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chanE.sph
wget    -P Signals/Bsr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Bsr001/chanF.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chan0.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chan2.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chan3.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chan6.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chan7.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chan9.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chanA.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chanB.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chanC.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chanD.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chanE.sph
wget    -P Signals/Btr001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr001/chanF.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chan3.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chan4.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chan5.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chan6.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chan7.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chan9.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chanA.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chanB.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chanC.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chanD.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chanE.sph
wget    -P Signals/Btr002 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Btr002/chanF.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chan0.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chan1.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chan2.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chan3.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chan6.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chan7.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chan8.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chan9.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chanA.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chanB.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chanC.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chanD.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chanE.sph
wget    -P Signals/Buw001 https://groups.inf.ed.ac.uk/ami//ICSIsignals/SPH/Buw001/chanF.sph
wget https://groups.inf.ed.ac.uk/ami//download/temp/icsiBuild-16548-Sun-Dec-4-2022.manifest.txt
wget https://groups.inf.ed.ac.uk/ami//download/temp/../CCBY4.0.txt
